### ISSUE TITLE
Slow compilation

### ISSUE THREAD

**Issue by benruijl** [Marwes/combine#123]
Since I switched my parser from nom to combine, the compilation time has increased dramatically (at least a factor 5). I think it has something to do with that almost all of my parsers are defined as closures, such as:

```
let keyword = |c| try(string_cmp(c, |l,r| l.eq_ignore_ascii_case(&r))).skip(not_followed_by(alpha_num())).skip(skipnocode());
````
Do you think this is correct? Will it help to rewrite most of the parsers into true functions?

**Comment by Marwes** [comment]
It might. In the past there has been the case that complex parsers caused typechecking times to blow up exponentially due to the large types combine creates (`Iterator` and `Future` adaptors has the same problem). Currently though, rustc is pretty good at memoizing typechecking results so it shouldn't be as big of an issue.

Still, it is almost unavoidable that combine will take a bit longer to compile as the types are more complex. Let me know what results you get if you convert them to free standing functions and remember to use the [parser!](https://docs.rs/combine/3.0.0-alpha.3/combine/macro.parser.html) macro!

(There was a few regressions in typechecking times in rustc over the last few months so you may also try compiling with the latest nightly which should have them all fixed).

**Comment by benruijl** [comment]
Rewriting all my closure functions to real functions decreased compilation time from 45 seconds down to 12 seconds!

**Comment by Marwes** [comment]
Great! That is much möte reasonable!
