### ISSUE TITLE
Regression in 3.3.4 (reached the instantiation recursion limit)

### ISSUE THREAD

**Issue by ordian** [Marwes/combine#172]
[toml_edit](https://github.com/ordian/toml_edit) fails to compile with combine `3.3.4`:
```
error: reached the recursion limit while instantiating `<parser::datetime::date_time<combine::easy::Stream<combine::stream::state::State<&str, combine::stream::state::SourcePosition>>> as combine::Parser>::parse_mode::<combine::parser::FirstMode>`
```

**Comment by Marwes** [comment]
It seems that 5257988c6419bd3e9c495400637c86e8e39e3133 increased the function nesting just enough to bring toml_edit over the recursion limit for monomorphizing (which seems to be 64). Increasing it with #![recursion_limit = "87"] seems to enough to make it compile again whereas 61 is enough with combine 3.3.1. Since the function that hit the limit is so close already I don't think I can fix this in combine unfortunately (without reverting the bug fix).

**Comment by ordian** [comment]
Ok, if it can't be reverted, I'm going to close this issue.

**Comment by Marwes** [comment]
@ordian I hoped an issue on rust-lang/rust to see why the limit is so low https://github.com/rust-lang/rust/issues/51951

**Comment by nikklassen** [comment]
I was also having this issue. I assume that the only solution is to convert a subset of the parsers to use Boxed parsers (given that the grammar I'm parsing can't change). Is that correct?

**Comment by Marwes** [comment]
@nikklassen You can bump the recursion limit by specifying `#![recursion_limit = "256"]` at your crate's root (default is 64 for this type of recursion).
