### ISSUE TITLE
Propagate error throught block

### ISSUE THREAD

**Issue by tailhook** [Marwes/combine#175]
Hi,

I have a problem with good error reporting. I'm parsing nginx config syntax which is basically:
```
directive1 args;
direcitve2 args;
```
And then there are blocks:
```
location / {
  directive1 args;
  directive2 args:
}
```
When bad directive is reached in a root context it reports a [nice error](https://github.com/tailhook/nginx-config/blob/master/tests/errors/invalid_directive.txt). 

But when parser encounters bad directive in a block:
```
location / {
  directive1 args;
  bad_directive;
}
```
It reports error as:
```
Unexpected `bad_directive`
Expected `BlockEnd`
```
I would like it to report `Expected("some_similar_directive")` messages too, but they got lost (I think) in `many` [combinator](https://github.com/tailhook/nginx-config/blob/master/src/grammar.rs#L172-L174).

I can probably make a small and self contained example to reproduce the issue, but I think I'm missing something small and simple. Any ideas?

**Comment by Marwes** [comment]
Seems to be caused by nested sequence parsers (tuples, and, skip, with ...) in some circumstances. Got a reproduction which I will look into which should hopefully be the same issue as this one.

**Comment by Marwes** [comment]
I think https://github.com/Marwes/combine/issues/175 should fix it but I am going to try some more test cases as well as there is likely more edge cases I have missed.

**Comment by tailhook** [comment]
At a glance, it doesn't work for me.

The code in place is this:
```
fn block() {
    (
        position(),
        kind(BlockStart)
            .with(many(parser(directive)))
            .skip(kind(BlockEnd)),
        position(),
    )
    .parse_stream(...)
}
fn directive(...) {
    position()
    .and(choice((
        [.. snip: lots of directives ..]
    )))
    .map(|(pos, dir)| ...)
    .parse_stream(input)
}
```
And a [link](https://github.com/tailhook/nginx-config/blob/master/src/grammar.rs#L172-L174).

Maybe I can change it somehow (except perhaps upgrading idioms a bit)?

**Comment by Marwes** [comment]
I think I see the issue now, going to need some effort to fix. Essentially `(many(x), end)` does not work with the current model if `many` has consumed input and then stops parsing at at something that is not `end`. In that case the parser has no idea that it expected either an `x` or an `end`.

It can't assume that the previous parser could have accepted more input since, if the first parser where not a repetition parser such as `(y, end)` then it should only report `expected end`. I need to thread some more information through to make the parser aware that the previous parser *or* the current parser expected something else.

**Comment by tailhook** [comment]
> The only thing that could maybe be a problem is that "function parsers" (as you use) are erasing the information needed to locate all the expected messages

I have a bunch of them in `choice((parser(x), parser(y)))` and that messages aren't canceled. So I doubt that. However, I can fix it if that could likely help.

> Essentially `(many(x), end)` does not work with the current model if `many` has consumed input and then stops parsing at at something that is not `end`.

Not sure I understand internals well, but I can do something like this:
```
many(choice((valid1, valid2, unexpected(...)))).skip(end())
```
... if that helps. I.e. `unexpected()` can hint some specific error rather than generic "next token doesn't match". And also it can specifically match everything except `end`, making it some kind of fatal error. But I'm not sure how to make use of that.

**Comment by Marwes** [comment]
I don't believe there is a way to solve this specific issue using any of the currently existing parsers. So the only fix is either adding something like `many_until(repeat_parser: P, end_parser: Q)` which are explicitly aware of this when generating errors messages or by making all combine parsers aware of this.

I think I have a solution for this which I will try and implement in the coming days or week.

**Comment by tailhook** [comment]
Yes, `many_until` is fine. Maybe we can also update `between` ?

**Comment by Marwes** [comment]
@tailhook I think the current implementation in 3.4 is the best that can be done with the current combine API. Barring any bugs where I have forgotten to forward a method call this should handle `(many(a), b)` and report `expected a or b` if it fails when trying to parse `b`, regardless of how `a` and `b` are sequenced (so `between` works).

The one caveat with this is that if `a` is created from a function using `parser` (as you do in this case), it is not possible for this to work. That is because the actual parser type of `a` is not accessible when `b` fails and I need to produce the error.

To work around this I added [opaque](https://docs.rs/combine/3.4.0/combine/parser/combinator/fn.opaque.html) as a way to erase the type while still keeping accessible enough for this error reporting to work. It has a slightly weird interface to make it all work though. ([`parser!](https://docs.rs/combine/3.4.0/combine/macro.parser.html) or `impl Parser` returning functions will also work if you are willing to accept macros or rust 1.26).

Let me know what works or doesn't if you try to use 3.4!

**Comment by Marwes** [comment]
And sorry for not responding here for a while, I were mostly offline for the better part of two weeks and then I have been trying to catch up again.

**Comment by tailhook** [comment]
Thanks!

It definitely works better. After converting to `impl Parser` I had to use `opaque` to get rid of infinitely recursive type, but that's okay (apart from rust, not reporting the error correctly). But now I have a problem with hiding errors on another level.

I have a large choice:
```
choice((
  # directives
  ident("location") .. ,
  ident("server_name") .. ,
  # modules
  some_module::directives(),
))
```
Where `some_module::directives()` contains another `choice(..)`. When using `parser(func)` it worked fine (internal directive names are propagated well), but after migrating to `impl Parser` the options that belong to nested `choice(..)` are absent in final error.

I use this kind of nested `choice(..)` for two reasons: (a) `choice(..)` has a limited maximum number of options and (b) just for better code structure. Maybe there is a better way to express it?

**Comment by Marwes** [comment]
`impl Parser` shouldn't have anything to do with it. I tried these two tests and the expected messages cover all the cases. 

```rust
let ident = |s| try(string(s));
let mut parser = choice((ident("aa"), choice((ident("bb"), ident("cc")))));
assert_eq!(parser.easy_parse("c").map_err(|e| e.errors), Err(vec![]));
```

```
let ident = |s| try(string(s));
let mut parser = choice((
    ident("aa"),
    opaque(|f| f(&mut choice((ident("bb"), ident("cc"))))),
));
assert_eq!(parser.easy_parse("c").map_err(|e| e.errors), Err(vec![]));
```

```rust
let ident = |s| try(string(s));
let mut parser = choice((
    ident("aa"),
    position().with(opaque(|f| {
        f(&mut no_partial(choice((ident("bb"), ident("cc")))))
    })),
    position().with(opaque(|f| {
        f(&mut no_partial(choice((ident("dd"), ident("ee")))))
    })),
));
assert_eq!(parser.easy_parse("c").map_err(|e| e.errors), Err(vec![]));
```

Are you able to get a smaller reproduction?

> (a) choice(..) has a limited maximum number of options

This could certainly be extended as well :)

**Comment by tailhook** [comment]
Yes, here is the example:
```
extern crate combine;

use combine::*;
use combine::parser::*;
use combine::parser::char::string;

fn bb<I>() -> impl Parser<Input = I, Output = ()>
    where I: Stream<Item = char>,
          // Necessary due to rust-lang/rust#24159
          I::Error: ParseError<I::Item, I::Range, I::Position>,
{
    let ident = |s| try(string(s));
    choice((
        ident("bb").map(|_| ()),
        ident("cc").map(|_| ())))
}

fn main() {
    let ident = |s| try(string(s));
    let mut parser = many::<Vec<_>, _>(position().and(choice((
        ident("aa").skip(string(";")).map(|_| ()),
        bb(),
    )))).skip(string("."));
    print!("Errors: {:#?}",
        parser.easy_parse("c").map_err(|e| e.errors));
}
```
If I remove `.skip()` it works fine, and if I retain skip but expand bb() into place it also works fine. But this specific combination doesn't work.

I don't understand why it's so, but hopefully, this example is helpful.

**Comment by tailhook** [comment]
Seems to work fine. Thanks!
