### ISSUE TITLE
`bytes()` shouldn't require range

### ISSUE THREAD

**Issue by starkat99** [Marwes/combine#249]
I'm writing a byte parser on a `Read` stream, so I do not have `RangeStream` available. Unfortunately, the `bytes()` (and `bytes_cmp()`) combinator requires a Range type of `&[u8]`, which I cannot get from a `ReadStream` (I did find it odd that `BufferedStream` didn't provide that, even if it wasn't a full `RangeStream`). It seems unnecessary for that combinator to require a slice range, especially when something like `string()` combinator does not. In the end, I had to use `tokens2(|a, b| *a == b, expected_bytes)` but that isn't going to give me great errors, plus it clones `expected_bytes` unnecessarily (which is unfortunate since I have a `&'static [u8]` for it) and is definitely not convenient.

**Comment by Marwes** [comment]
Usually the recommendation has been to set `Stream::Item == Stream::Range` if the `Stream` can't implement `RangeStream`. I didn't consider that a proper `Range` could be useful in the error then however so it seems fine to make it a `&'static [u8]` in that case.

The same thing would be useful for `IteratorStream` but unfortunately that can't work since the `Item` may not be `'static`.
