### ISSUE TITLE
Wrong output of combine::parser::combinator::recognize

### ISSUE THREAD

**Issue by kompass** [Marwes/combine#256]
Hello,

I discovered a bug in `combine::parser::combinator::recognize`. I don't use the "range" version of this function because I work with `IteratorStream`.

When I do 

```rust
let expr = many1::<String, _>(digit());
let expr_mapped = expr.map(|s| { dbg!(s) });
```

, and I parse a number with expr_mapped, I obtain the good output.

When I replace the first line by

```rust
let expr = recognize(skip_many1(digit()));
```
and I reparse the same numbers, the `String` is sometimes empty.

I discovered that when the length of the parsed string exceeds the length of BufferedStream, the returned string is empty. We should rather have an error, right ?

**Comment by Marwes** [comment]
Sorry for forgetting to respond to this. I did some testing and this is fixed in version 4.x as "resetting" the stream to a previous location were allowed to fail there which properly emits an error in this case. It might be possible to hack something into 3.x as well but I haven't truly looked into it.

Does 4.x work for you?

**Comment by kompass** [comment]
I didn't test 4.x for now since it's still in alpha but I may be testing in the coming days.
I corrected the bug in my case using only the `count` and derived parsing methods with the size of the buffer as an argument. For now it works perfectly.

Thank you
