### ISSUE TITLE
`Range` is not `Clone`

### ISSUE THREAD

**Issue by netvl** [Marwes/combine#282]
It seems that [Range](https://docs.rs/combine/4.0.1/combine/parser/range/struct.Range.html) is not `Clone`, so you can't do a lot of useful things in the streaming mode now. I'm not sure if this is deliberate, because I don't see any issues with it being `Clone` as long as the range is cloneable (and it should be, because `StreamOnce::Range` is marked as `Clone`).

**Comment by Marwes** [comment]
I am not opposed to adding it but since parser aren't cloneable in general I would usually recommend that any parsers that you need to use more than once are instead wrapped in a function/closure and you instead invoke it multiple times instead of cloning.

https://github.com/mitsuhiko/redis-rs/blob/b4cccdfbabf75400636508d90115a21620af8616/src/parser.rs#L64-L68

**Comment by netvl** [comment]
Ok, makes sense as a workaround, I guess. I think in similar situations (not with `combine` but with other code) I encountered some issues with such approach, but I don't remember exactly what. I guess I'll try and see now :)

**Comment by netvl** [comment]
Maybe it would make sense to make it consistent and remove all `Clone` impls, and provide a warning in documentation about the recommended approach?

**Comment by Marwes** [comment]
Maybe, but it would be a breaking change for little gain :man_shrugging: . Just released 4.0 so it is going to be a while (if ever) that another breaking change can happen

**Comment by netvl** [comment]
Wrapping parses in closures to "clone" them seems to work for me, BTW. I guess this can be closed?
