### ISSUE TITLE
Fast string search?

### ISSUE THREAD

**Issue by ArtemGr** [Marwes/combine#39]
I wonder if you use or could use something like https://github.com/shepmaster/jetscii for some of the matching primitives?

**Comment by Marwes** [comment]
I don't use anything like that currently, it seems like it reads 16 bytes at a time which is not really compatible with the `Stream` interface I use currently which just takes one token at a time instead of looking at a whole range. I will keep the ability to use custom searchers such as jetscii when working on ranged streams (for lack of a better name).

I have some WIP at https://github.com/Marwes/combine/tree/range_stream though I am not really happy with that interface right now.

**Comment by Marwes** [comment]
That being said, since that search is specialized on `&str` you could just circumvent the `Stream` trait and write your own parser which is specialized only on `&str` which calls the `find` method and if it succeeds just skips ahead to index that is returned, you just need to remember to update the position as well.

**Comment by ArtemGr** [comment]
> which is not really compatible with the Stream interface I use currently which just takes one token at a time

I suspected as much. Most parsers just take one token at a time.
Thanks for answering.
