### ISSUE TITLE
How do I create my own char parsers?

### ISSUE THREAD

**Issue by idmit** [Marwes/combine#40]
I can't understand how to define something simple, for example, [oneOf](https://hackage.haskell.org/package/parsec-3.1.7/docs/Text-Parsec-Char.html#v:oneOf) equivalent.   
Can you help me out? :disappointed:

**Comment by Marwes** [comment]
[satisfy](https://marwes.github.io/combine/combine/fn.satisfy.html) takes a function in which you can use to check anything on a token so `satisfy(|c| "abc123".chars().any(|o| o == c))` Should do the trick, it doesn't give the best error information though so you might want to attach a message which is added when it fails to match as well. `satisfy(|c| "abc123".chars().any(|o| o == c)).expected("expected message")`.

**Comment by Marwes** [comment]
I have an open issue for adding parsers from parsec so feel free to comment if you see one you feel should be added. I didn't add `oneOf` earlier since giving it proper error messages would be rather expensive (one error/token you test for) though I think that is less of an issue now after the `parse_lazy` method is added.

**Comment by Marwes** [comment]
Closing due to inacivity, feel free to reopen if it didn't answer your question
