### ISSUE TITLE
"choice" / "or" examples missing "try" ?

### ISSUE THREAD

**Issue by acdimalev** [Marwes/combine#53]
I just had a heck of a time figuring out why the following examples both yield errors:

```rust
choice([
    string("one"),
    string("two"),
    string("three"),
]).parse("two");
```

```rust
string("this").or(string("that")).parse("that");
```

From what I can tell, for either of these examples to work properly, they need to be written as follows:

```rust
choice([
    try(string("one")),
    try(string("two")),
    try(string("three")),  // optional, but nice for consistency
]).parse("two");
```

```rust
try(string("this")).or(string("that")).parse("that");
```

I'm not sure which behavior is desirable / whether it's the documentation or the code that should be updated.  In either case, I would be happy to take a stab at throwing together some pull requests here.  Combine has been saving me a ton of hassle.

**Comment by Marwes** [comment]
I think it is the documentation that should be changed in this case to make it more explicit that having two parsers in `choice`/`or` which have the same prefix will cause trouble. I tried to express that in the documentation but looking at it now it could probably be clearer. Feel free to submit a PR improving it if you like. I may take a look at sometime next week otherwise.

**Comment by Marwes** [comment]
Closing. Feel free to reopen if the documentation is still confusing.
