### ISSUE TITLE
Type mismatch when using sep_by

### ISSUE THREAD

**Issue by mechaxl** [Marwes/combine#59]
Not sure if this is a bug, but it seems like it should work. This code fails to compile:

```rust
extern crate combine;
use combine::{digit, letter, sep_by, token, Parser, ParserExt};

fn main() {
    let p = sep_by::<Vec<_>, _, _>(digit(), token(','));
    let result = letter().or(p).parse("1,2,3");
}
```

With this error:

```rust
type mismatch resolving `<&str as combine::primitives::Stream>::Item == collections::vec::Vec<char>`:
 expected char,
    found struct `collections::vec::Vec` [E0271]
src/main.rs:6     let result = letter().or(p).parse("1,2,3");
```

However, this works just fine:

```rust
extern crate combine;
use combine::{digit, letter, token, Parser, ParserExt};

fn main() {
    let result = letter().or(digit()).parse("1,2,3");
}
```

**Comment by Marwes** [comment]
In this case it seems that the error message is a bit confusing but the issue is that `letter()` outputs a `char` while `sep_by` outputs a `Vec` and `or` requires that both parsers outputs the same type. I am not sure what you want to output in this case but this thread about an expression parser might help as well https://github.com/Marwes/combine/issues/54

**Comment by mechaxl** [comment]
Thanks for the reply. Ultimately, what I'm trying to do is parse a string consisting of letters with optional arguments lists, like this: `ABA(1, 2)C(3)DE(4, 5, 6)C`. Reading over the thread you linked, it looks like I'll want to make an enum to represent both options. Thanks!
