### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by Yamakaky** [Marwes/combine#71]
Does your crate support Unicode character classes and normalization?

**Comment by Marwes** [comment]
No, you will have to look into some other crate for that. You can then use `satisfy(|token| predicate(token)).expected("Expected value")` to create a custom parser for whatever predicate you want (`digit`, `letter` etc are all implemented like this)

**Comment by jan-hudec** [comment]
For classes only, yes. For normalisation, no, one would have to write a new parser using the [unicode-normalization](https://crates.io/crates/unicode-normalization) crate, because a `token` here means a single codepoint (`char`), but normalisation needs to see multiple-codepoint sequences.

In fact I tried—and failed (#85)—at similar thing with graphemes and [unicode-segmentation](https://crates.io/crates/unicode-segmentation) yesterday.

**Comment by Marwes** [comment]
To get regex parsers working I added [FullRangeStream](https://docs.rs/combine/2.5.0/combine/primitives/trait.FullRangeStream.html) which lets one get retrieve a view into the entire parsers input.
Since unicode parsers require `&str` then this can be used to write parsers generic over the input stream (translating the example in https://github.com/Marwes/combine/issues/85#issuecomment-280167581.

```rust
pub fn grapheme<'a, I>(input: I) -> ParseResult<&'a str, I>
    where I: FullRangeStream<Range = &'a str>
{
    let mut iter = input.range().graphemes();
    match iter.next() {
        Some(g) => {
            let len = input.range().len() - iter.as_str().len();
            take(len).parse_stream(input)
        }
        None => Err(ParseError::end_of_input()),
    }
}
```
