### ISSUE TITLE
Document the role of PhantomType/PhantomData

### ISSUE THREAD

**Issue by ncalexan** [Marwes/combine#78]
Hi @Marwes, you've been so helpful understanding `combine` that I wonder if you could save me some more experimentation.  Can you explain why `PhantomType` and `PhantomData` are present in the codebase?  I'm aware this works around some limitations in the Rust type checker but it would help to spell out the motivating case for `combine`.  If you can explain or link to the relevant changesets, I will try to add a note to the README.  Thanks!

**Comment by Marwes** [comment]
Not a problem.

Consider [Take](https://github.com/Marwes/combine/blob/1004cbe9a4be518be8aa96cc2810e649cb0d5127/src/range.rs#L56-L72) which uses `PhantomData` for the `I : RangeStream` parameter since Rust requires that all type paramters of a type is actually used in the type itself.

```rust

pub struct Take<I>(usize, PhantomData<fn(I) -> I>);
impl<I> Parser for Take<I>
    where I: RangeStream,
          I::Range: ::primitives::Range
{
    type Input = I;
    type Output = I::Range;

    fn parse_lazy(&mut self, mut input: Self::Input) -> ConsumedResult<Self::Output, Self::Input> {
        ...
    }
}
```

So why can't we just have `pub struct Take(usize);` ?

Well, the `Parser` implementation uses `I` for its associated `Input` type and all associated types must be fully specified from the `Self` type (`Take<I>`). If `I` did not appear in `Take` Rust rejects the `impl` as you could have `Take : Parser<Input = &str>` and `Take : Parser<Input = &[u8]>` etc.

It is actually possible to be a bit more clever and move `Input` to a trait parameter instead as below which will let use remove the `I` parameter and I have actually tried doing that in the past. However it turns out that if `Parser` is implemented as below rust can start failing to infer the correct type for `Input` in not to uncommon cases and the only way to resolve that is to force users to add type annotations which is not particularly user friendly.

```

impl<I> Parser<I> for Take
    where I: RangeStream,
          I::Range: ::primitives::Range
{
    type Output = I::Range;

    fn parse_lazy(&mut self, mut input: I) -> ConsumedResult<Self::Output, I> {
        ...
    }
}
```

Anyways, that is the gist of it. Do you have any reason other than curiosity towards this? I feel its more of an implementation detail so I am not sure it belongs in the README since it is really just an implementation detail. (Not that implementation details are worth documenting. I guess as long as it is not front and center it can belong there).

**Comment by ncalexan** [comment]
@Marwes wow, great answer.  Thanks for being so responsive!

> Do you have any reason other than curiosity towards this?

Not really.  I wrote a small combinator and really had to dig into the source to understand some subtleties (confounded by this being my "learn Rust!" project), so I wanted to really understand what was going on in the guts.

> I feel its more of an implementation detail so I am not sure it belongs in the README since it is really just an implementation detail. (Not that implementation details are worth documenting. I guess as long as it is not front and center it can belong there).

I'm fine with this.  I prefer to phrase tickets/issues as "complete this action" or "solve this problem", so I phrased my question as "document this curiousity" rather than "answer my question".  But you've answered my question and we can link to this discussion rather than fold it into the README as you see fit.
